config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_page#home'
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  get '/logout', to:'sessions#destroy'

  resources :users do
    resources :posts, only: [:index, :new, :create]
    resources :book_marks, only: :index
    resources :relationships, only: [:create, :destroy]
    resources :followings, only: :index, module: :users
    resources :followers, only: :index, module: :users
    resources :messages, only: [:index, :create, :show]
    resources :drafts, only: :index, module: :posts
  end

  resources :posts, only: :show do
    resources :comments, only: [:new, :create]
    resources :book_marks, only: [:create, :destroy]
    resources :reposts, only: [:new, :create], module: :posts
  end

  resources :comments, only: :show do
    resources :replies, only: [:new, :create]
  end

  resources :search_users, only: :index, module: :users
  resources :search_posts, only: :index, module: :posts
  resources :drafts, only: [:edit, :update], module: :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :replies, dependent: :destroy
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.build(comment_params)
    @comment.post = @post

    if @comment.save
      flash[:success] = 'success in commenting'
      redirect_to post_url(params[:post_id])
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.find(params[:id])
    @replies = @comment.replies.includes(:user)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.slim
= provide(:title, 'New comment')
.container
  h1
    | New Comment
    .row
      .col-md-6
        = render 'shared/error_messages', object: @comment
        = render 'shared/comment_form', object: @comment, url: post_comments_path(@post.id)

app/views/comments/show.html.slim
= provide(:title, :Comment)
.container
  .row
    .comment
      p
        | 投稿者
        = link_to @comment.user.name, @comment.user
      p = @comment.content
      p = l @comment.created_at

    - @replies.each do |reply|
      .comment
        p
          | 投稿者
          = link_to reply.user.name, reply.user
        p = reply.content
        p = l reply.created_at

    p = link_to '返信する', new_comment_reply_path(@comment.id)