config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_page#home'
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  get '/logout', to:'sessions#destroy'

  resources :users do
    resources :posts, only: [:index, :new, :create]
    resources :book_marks, only: :index
    resources :relationships, only: [:create, :destroy]
    resources :followings, only: :index, module: :users
    resources :followers, only: :index, module: :users
    resources :messages, only: [:index, :create, :show]
    resources :drafts, only: :index, module: :posts
  end

  resources :posts, only: :show do
    resources :comments, only: [:new, :create]
    resources :book_marks, only: [:create, :destroy]
    resources :reposts, only: [:new, :create], module: :posts
  end

  resources :comments, only: :show do
    resources :replies, only: [:new, :create]
  end

  resources :search_users, only: :index, module: :users
  resources :search_posts, only: :index, module: :posts
  resources :drafts, only: [:edit, :update], module: :posts
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :book_marks, dependent: :destroy
  has_many :book_marked_posts, through: :book_marks, source: :post
  has_many :active_relationships, class_name: :Relationship,
                   foreign_key: :follower_id,
                   dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: :Relationship,
                   foreign_key: :followed_id,
                   dependent: :destroy
  has_many :followers, through: :passive_relationships
  has_many :send_messages, class_name: :Message,
                foreign_key: :sender_id,
                dependent: :destroy
  has_many :received_message_users, through: :send_messages, source: :receiver
  has_many :receive_messages, class_name: :Message,
                foreign_key: :receiver_id,
                dependent: :destroy
  has_many :sent_message_users, through: :receive_messages, source: :sender

  before_save { self.email = email.downcase }

  validates :name,  presence: true
  validates :email, presence: true, uniqueness: true
  validates :intro, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, format: { with: /[A-Z]\w+/,
    message: 'the first letter must be upcase' }

  scope :in_ids, -> (_ids){ where(id: _ids) }
  scope :match_by_name, ->(name){ where("name like ?", name)}
  scope :exclude_name, ->(name){ where.not("name like ?", name)}

  mount_uploader :image, ImageUploader
  include SessionsHelper

  def text_slice
    intro.length > 25 ? "#{intro.slice(0..24)}..." : intro
  end

  def following_count
    "#{followings.count}following"
  end

  def followers_count
    "#{followers.count}followers"
  end

  def communicated_users
    self.class.in_ids(communicated_user_ids)
  end

  private

  def communicated_user_ids
    (received_message_user_ids + sent_message_user_ids).uniq
  end

  def received_message_user_ids
    received_message_users.pluck(:id)
  end

  def sent_message_user_ids
    sent_message_users.pluck(:id)
  end
end

app/controllers/users/followers_controller.rb
class Users::FollowersController < ApplicationController
  def index
    @users = User.find(params[:user_id]).followers
  end
end

app/controllers/users/followings_controller.rb
class Users::FollowingsController < ApplicationController
  def index
    @users = User.find(params[:user_id]).followings
  end
end

app/controllers/users/search_users_controller.rb
class Users::SearchUsersController < ApplicationController

  include SearchKeywordConvertable

  def index
    @users = fetch_users(params[:search_method], params[:name])
    render 'users/index'
  end

  private

  def fetch_users(search_method, name)
    if name.empty?
      fetch_all_users
    else
      fetch_users_by(search_method, name)
    end
  end

  def fetch_all_users
    User.all
  end

  def fetch_users_by(search_method, name)
    unless search_method === 'exclude'
      fetch_users_by_user_name(search_method, name)
    else
      fetch_users_by_excluding(name)
    end
  end

  def fetch_users_by_user_name(search_method, name)
    keyword = convert_keyword(search_method, name)
    User.match_by_name(keyword)
  end

  def fetch_users_by_excluding(name)
    User.exclude_name(name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :logged_in_user, only: [:new, :create, :show, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user?, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
    @title = 'All Users'
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome to The Cities!!!!"
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = user
    @posts = @user.posts.published
    @relationship_id = Relationship.find_by_id(current_user.id, @user.id)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update_attributes(user_params)
      flash[:success] = "Update Profile!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user.destroy
    flash[:success] = 'success!'
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :intro, :image, :password, :password_confirmation)
  end

  def correct_user
    unless current_user?
      flash[:danger] = "You can't  edit"
      redirect_to root_path
    end
  end

  def current_user?
    current_user == user
  end

  def admin_user?
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/users/followers_helper.rb
module Users::FollowersHelper
end

app/helpers/users/followings_helper.rb
module Users::FollowingsHelper
end

app/helpers/users/search_users_helper.rb
module Users::SearchUsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user
    User.find(params[:id])
  end

  def edit_user_link(user)
    render 'shared/edit_user_link' if current_user == user
  end

  def delete_user_link(user)
    link_to "削除", user_path(user), method: :delete, data: { confirm: "You sure" } if current_user.admin? && !current_user?(user)
  end

  def image(user)
    image_tag user.image.thumb30.url if user.image?
  end

  def send_message_link(user_id, other_user_id)
    link_to 'メッセージを送る', user_message_path(user_id, other_user_id) unless user_id == other_user_id
  end
end

app/views/users/edit.html.slim
= provide(:title, 'Edit Profile')
.container
  h1
    | Edit Profile
  .row
    .col-md-6
      = render 'shared/error_messages', object: @user
      = form_for @user, url: user_path(@user.id) do |f|
        .form
          = f.label "画像をアップロード"
          br
          = f.file_field :image
        .form
          = f.label :name
          = f.text_field :name, size: 40
        .form
          = f.label :email
          = f.text_field :email, size: 40
        .form
          = f.label :intro
          = f.text_area :intro, size: "40*100"
        .form
          = f.label :password
          = f.password_field :password, size: 40
        .form
          = f.label :password_confirmation, "Confirmation"
          = f.password_field :password_confirmation, size: 40
        .form
          = f.submit 'udpate', class: "btn"

app/views/users/index.html.slim
= provide(:title, 'All Users')
.container
  = form_with url: search_users_path, method: :get, local: true do |f|
    = f.label :ユーザー名
    = f.text_field :name, size: "40*10", value: :検索したいユーザー名を入力してみよう
    = f.label :前方一致
    = f.radio_button :search_method, :forward_match, checked: true
    = f.label :後方一致
    = f.radio_button :search_method, :backward_match
    = f.label :完全一致
    = f.radio_button :search_method, :perfect_match
    = f.label :対象外
    = f.radio_button :search_method, :exclude
    = f.submit 'search', class: :btn, name:nil
  h1
    | All Users
  = render partial: 'shared/user', collection: @users

app/views/users/new.html.slim
= provide(:title, 'Sign up')
.container
  h1
    | Sign Up
  .row
    .col-md-6
      = render 'shared/error_messages', object: @user
      = render 'shared/user_form', path: signup_path, button: "Create my account"

app/views/users/show.html.slim
= provide(:title, @user.name)
.container
  = render 'shared/user_show', collection: @user
  h2
    | 全ての投稿
    = link_to 'ブックマーク', user_book_marks_path(@user)
  .posts
    = render partial: 'shared/post', collection: @posts