config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_page#home'
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  get '/logout', to:'sessions#destroy'

  resources :users do
    resources :posts, only: [:index, :new, :create]
    resources :book_marks, only: :index
    resources :relationships, only: [:create, :destroy]
    resources :followings, only: :index, module: :users
    resources :followers, only: :index, module: :users
    resources :messages, only: [:index, :create, :show]
    resources :drafts, only: :index, module: :posts
  end

  resources :posts, only: :show do
    resources :comments, only: [:new, :create]
    resources :book_marks, only: [:create, :destroy]
    resources :reposts, only: [:new, :create], module: :posts
  end

  resources :comments, only: :show do
    resources :replies, only: [:new, :create]
  end

  resources :search_users, only: :index, module: :users
  resources :search_posts, only: :index, module: :posts
  resources :drafts, only: [:edit, :update], module: :posts
end

app/views/shared/_comment_form.html.slim
= form_with model: object, url: url do |f|
  .form
    = f.label :本文
    = f.text_area :content, size: '40*100'
  .form
    = f.submit 'comment', class: 'btn'

app/views/shared/_delete_user_link.html.slim
= link_to '削除', user

app/views/shared/_edit_user_link.html.slim
= link_to 'プロフィールを編集または追記する', edit_user_path(current_user.id)

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  div
    |  The form contains 
    = pluralize(object.errors.count, 'error')
    | . 
    ul
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/shared/_flash.html.slim
- flash.each do |type, msg|
  li
    = msg

app/views/shared/_post.html.slim
.post
  .post-content
    = image post
  .post-content
    p = link_to post.user.name, user_path(post.user.id)
    p.break = shorted_text post
    p = l post.created_at
    = link_to '詳細をみる', post

app/views/shared/_post_detail.html.slim
p
  | 投稿者
  = link_to post.user.name, post.user
= image post
p = post.content
p = l post.created_at

app/views/shared/_post_form.html.slim
= form_with model: model, url: url, local: true do |f|
  .form
    = f.label :本文
    = f.text_area :content, size: "40*100", value: model.content
  .form
    = f.label "画像をアップロード"
    = f.file_field :image
  .draft
    = f.label :下書きとして保存する
    = f.radio_button :status, :draft
  .draft
    = f.label :タイムラインに投稿する
    = f.radio_button :status, :published, checked: true
  .form
    = f.submit 'post', class: "btn"

app/views/shared/_reaction_to_post.html.slim
p.contact = link_to 'コメントする', new_post_comment_url(post.id)
- if @book_mark_id.nil?
  p.contact = link_to 'ブックマークする', post_book_marks_url(post.id), method: :post
- else
  p.contact = link_to 'ブックマークを取り消す', post_book_mark_url(post.id, @book_mark_id), method: :delete
- if post.parent?
  p.contact = link_to 'リポストする', new_post_repost_url(post.id)

app/views/shared/_signup_link.html.slim
= link_to 'Sign up', signup_path, class:"btn"

app/views/shared/_user_form.html.slim
= form_for @user, url: path do |f|
  .form
    = f.label :name
    = f.text_field :name, size: 40
  .form
    = f.label :email
    = f.text_field :email, size: 40
  .form
    = f.label :intro
    = f.text_area :intro, size: "40*100"
  .form
    = f.label :password
    = f.password_field :password, size: 40
  .form
    = f.label :password_confirmation, "Confirmation"
    = f.password_field :password_confirmation, size: 40
  .form
    = f.submit button, class: "btn"

app/views/shared/_user_show.html.slim
  .profiles
    .image
      = image @user
    .name
      h1
        = @user.name
      p.break
        = @user.intro
      p
        = follow_or_unfollow_link(current_user.id, @user.id, @relationship_id)
      p.relation
        = link_to @user.following_count, user_followings_path(@user)
      p.relation
        = link_to @user.followers_count, user_followers_path(@user)
      p = send_message_link(current_user.id, @user.id)
  p
    = edit_user_link @user

app/views/shared/_when_login_link.html.slim
= link_to current_user.name, current_user
= link_to '投稿する', new_user_post_path(current_user.id)
= link_to '下書きを編集する', user_drafts_path(current_user.id)
= link_to 'ユーザー一覧', users_path
= link_to 'タイムライン', user_posts_path(current_user.id)
= link_to 'ダイレクトメッセージ', user_messages_path(current_user.id)
= link_to 'log out', '/logout'

app/views/shared/_when_not_login_link.html.slim
= link_to 'log in', '/login'