config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_page#home'
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  get '/logout', to:'sessions#destroy'

  resources :users do
    resources :posts, only: [:index, :new, :create]
    resources :book_marks, only: :index
    resources :relationships, only: [:create, :destroy]
    resources :followings, only: :index, module: :users
    resources :followers, only: :index, module: :users
    resources :messages, only: [:index, :create, :show]
    resources :drafts, only: :index, module: :posts
  end

  resources :posts, only: :show do
    resources :comments, only: [:new, :create]
    resources :book_marks, only: [:create, :destroy]
    resources :reposts, only: [:new, :create], module: :posts
  end

  resources :comments, only: :show do
    resources :replies, only: [:new, :create]
  end

  resources :search_users, only: :index, module: :users
  resources :search_posts, only: :index, module: :posts
  resources :drafts, only: [:edit, :update], module: :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :child_post, class_name: :Post, foreign_key: :parent_id, dependent: :destroy
  belongs_to :parent_post, class_name: :Post, foreign_key: :parent_id, optional: true
  has_many :comments, dependent: :destroy
  has_many :book_marks, dependent: :destroy
  has_many :book_marked_users, through: :book_marks, source: :user

  enum status: [:published, :draft]

  default_scope -> { order(created_at: :desc) }
  scope :match_by_user, ->(user_ids){ where(user_id: user_ids)}
  scope :match_by_content, ->(keyword){ where("content like ?", keyword)}
  scope :fetch_only_draft, ->(user_id){ where(user_id: user_id).draft}

  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  validates :image, presence: true

  mount_uploader :image, ImageUploader

  def self.find_posts(following_ids)
    where(user_id: following_ids).includes(:user)
  end

  def text_slice
    content.length > 50 ? "#{content.slice(0..19)}..." : content
  end

  def parent?
    parent_id.nil?
  end
end

app/controllers/posts/drafts_controller.rb
class Posts::DraftsController < ApplicationController
  before_action :fetch_draft, only: [:edit, :update]

  def index
    @drafts = Post.match_by_user(params[:user_id]).draft
  end

  def edit
  end

  def update
    if @draft.update_attributes(draft_params)
      redirect_to @draft.user
    else
      render 'edit'
    end
  end

  private

  def draft_params
    params.require(:post).permit(:content, :image, :status)
  end

  def fetch_draft
    @draft = Post.find(params[:id])
  end
end

app/controllers/posts/reposts_controller.rb
class Posts::RepostsController < ApplicationController
  before_action :find_parent_post

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(repost_params).tap do |post|
      post.parent_post = @parent_post
    end

    if @post.save
      flash[:success] = 'success in reposting'
      redirect_to current_user
    else
      render 'new'
    end
  end

  private

  def find_parent_post
    @parent_post = Post.find(params[:post_id])
  end

  def repost_params
    params.require(:post).permit(:content, :image)
  end
end

app/controllers/posts/search_posts_controller.rb
class Posts::SearchPostsController < ApplicationController

  include SearchKeywordConvertable

  def index
    @posts = fetch_posts(params[:keyword], params[:search_method])
    render 'posts/index'
  end

  private

  def fetch_posts(keyword, search_method)
    if keyword.empty?
      fetch_all_posts
    else
      fetch_postss_by(keyword, search_method)
    end
  end

  def fetch_all_posts
    Post.all.includes(:user).published
  end

  def fetch_postss_by(keyword, search_method)
    if search_method == 'user_match'
      fetch_posts_by_user_name(keyword)
    else
      fetch_posts_by_content(keyword, search_method)
    end
  end

  def fetch_posts_by_user_name(keyword)
    user_ids = User.match_by_name(keyword).pluck(:id)
    Post.match_by_user(user_ids).includes(:user).published
  end

  def fetch_posts_by_content(keyword, search_method)
    keyword = convert_keyword(search_method, keyword)
    Post.match_by_content(keyword).includes(:user).published
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.find_posts(current_user.followings.ids.push current_user.id).published
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = 'succeed in posting'
      redirect_to current_user
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user)
    @book_mark_id = BookMark.find_by(user_id: current_user.id, post_id: @post.id)&.id
  end

  private

  def post_params
    params.require(:post).permit(:content, :image, :status)
  end
end

app/helpers/posts/drafts_helper.rb
module Posts::DraftsHelper
end

app/helpers/posts/reposts_helper.rb
module Posts::RepostsHelper
end

app/helpers/posts/search_posts_helper.rb
module Posts::SearchPostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def new_or_show_reply(comment)
    if comment.replies.empty?
      link_to 'スレッドを開始する', new_comment_reply_path(comment.id)
    else
      link_to 'スレッドをみる', comment_path(comment.id)
    end
  end
end

app/views/posts/index.html.slim
= provide(:title, 'All posts')
.container
  = form_with url: search_posts_path, method: :get, local: true do |f|
    = f.label :キーワード
    = f.text_field :keyword, size: "40*10", value: :検索したいキーワードを入力してください
    = f.label :ユーザー名で絞り込む
    = f.radio_button :search_method, :user_match
    = f.label :投稿で絞り込む
    = f.radio_button :search_method, :content_match, checked: true
    = f.submit 'search', class: :btn, name:nil
  h2
    | TimeLine
  .posts
    = render partial: 'shared/post', collection: @posts

app/views/posts/new.html.slim
= provide(:title, 'New post')
.container
  h1
    | New Post
    .row
      .col-md-6
        = render 'shared/error_messages', object: @post
        = render 'shared/post_form', model: @post, url: user_posts_path(current_user.id)

app/views/posts/show.html.slim
= provide(:title, :Post)
.container
  .row
    -if @post.parent?
      .content
        = render 'shared/post_detail', post: @post
        = render 'shared/reaction_to_post', post: @post
    -else
      .repost-content
        = render 'shared/post_detail', post: @post
        = render 'shared/post', post: @post.parent_post
        = render 'shared/reaction_to_post', post: @post

    - if @comments.empty?
      h3 コメントはありません
    - else
      h3
        | コメント一覧
        - @comments.each do |comment|
          .comment
            p
              | 投稿者
              = link_to comment.user.name, comment.user
            p = comment.content
            p = l comment.created_at
            p = new_or_show_reply(comment)